# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\data_opening.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataWindow(object):
    def setupUi(self, DataWindow):
        DataWindow.setObjectName("DataWindow")
        DataWindow.resize(888, 452)
        self.centralwidget = QtWidgets.QWidget(DataWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_13 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.selected_data = QtWidgets.QListWidget(self.groupBox_13)
        self.selected_data.setDragEnabled(False)
        self.selected_data.setDragDropOverwriteMode(False)
        self.selected_data.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.selected_data.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.selected_data.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.selected_data.setLayoutMode(QtWidgets.QListView.Batched)
        self.selected_data.setObjectName("selected_data")
        self.horizontalLayout_11.addWidget(self.selected_data)
        self.verticalLayout_7.addWidget(self.groupBox_13)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.data_info = QtWidgets.QTextEdit(self.groupBox)
        self.data_info.setObjectName("data_info")
        self.horizontalLayout.addWidget(self.data_info)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.opened_functions = QtWidgets.QListWidget(self.groupBox_12)
        self.opened_functions.setDragEnabled(False)
        self.opened_functions.setDragDropOverwriteMode(False)
        self.opened_functions.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.opened_functions.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.opened_functions.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.opened_functions.setLayoutMode(QtWidgets.QListView.Batched)
        self.opened_functions.setObjectName("opened_functions")
        self.horizontalLayout_10.addWidget(self.opened_functions)
        self.verticalLayout_6.addWidget(self.groupBox_12)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.load_label_14 = QtWidgets.QLabel(self.centralwidget)
        self.load_label_14.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_label_14.sizePolicy().hasHeightForWidth())
        self.load_label_14.setSizePolicy(sizePolicy)
        self.load_label_14.setAutoFillBackground(True)
        self.load_label_14.setObjectName("load_label_14")
        self.horizontalLayout_29.addWidget(self.load_label_14)
        self.function_file_path = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.function_file_path.sizePolicy().hasHeightForWidth())
        self.function_file_path.setSizePolicy(sizePolicy)
        self.function_file_path.setText("")
        self.function_file_path.setObjectName("function_file_path")
        self.horizontalLayout_29.addWidget(self.function_file_path)
        self.browse_function = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_function.sizePolicy().hasHeightForWidth())
        self.browse_function.setSizePolicy(sizePolicy)
        self.browse_function.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/browse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse_function.setIcon(icon)
        self.browse_function.setObjectName("browse_function")
        self.horizontalLayout_29.addWidget(self.browse_function)
        self.verticalLayout_6.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_20.addWidget(self.label)
        self.function_id = QtWidgets.QLineEdit(self.centralwidget)
        self.function_id.setObjectName("function_id")
        self.horizontalLayout_20.addWidget(self.function_id)
        self.add_function = QtWidgets.QPushButton(self.centralwidget)
        self.add_function.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_function.setIcon(icon1)
        self.add_function.setObjectName("add_function")
        self.horizontalLayout_20.addWidget(self.add_function)
        self.rm_function = QtWidgets.QPushButton(self.centralwidget)
        self.rm_function.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rm_function.setIcon(icon2)
        self.rm_function.setObjectName("rm_function")
        self.horizontalLayout_20.addWidget(self.rm_function)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_9.addWidget(self.label_35)
        self.plot_id = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_id.sizePolicy().hasHeightForWidth())
        self.plot_id.setSizePolicy(sizePolicy)
        self.plot_id.setObjectName("plot_id")
        self.horizontalLayout_9.addWidget(self.plot_id)
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_9.addWidget(self.label_36)
        self.data_id = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_id.sizePolicy().hasHeightForWidth())
        self.data_id.setSizePolicy(sizePolicy)
        self.data_id.setObjectName("data_id")
        self.horizontalLayout_9.addWidget(self.data_id)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.data_label = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_label.sizePolicy().hasHeightForWidth())
        self.data_label.setSizePolicy(sizePolicy)
        self.data_label.setObjectName("data_label")
        self.horizontalLayout_9.addWidget(self.data_label)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.data_R_n = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_R_n.sizePolicy().hasHeightForWidth())
        self.data_R_n.setSizePolicy(sizePolicy)
        self.data_R_n.setMaximum(255)
        self.data_R_n.setObjectName("data_R_n")
        self.horizontalLayout_9.addWidget(self.data_R_n)
        self.data_G_n = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_G_n.sizePolicy().hasHeightForWidth())
        self.data_G_n.setSizePolicy(sizePolicy)
        self.data_G_n.setMaximum(255)
        self.data_G_n.setObjectName("data_G_n")
        self.horizontalLayout_9.addWidget(self.data_G_n)
        self.data_B_n = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_B_n.sizePolicy().hasHeightForWidth())
        self.data_B_n.setSizePolicy(sizePolicy)
        self.data_B_n.setMaximum(255)
        self.data_B_n.setProperty("value", 255)
        self.data_B_n.setObjectName("data_B_n")
        self.horizontalLayout_9.addWidget(self.data_B_n)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.browse_color = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_color.sizePolicy().hasHeightForWidth())
        self.browse_color.setSizePolicy(sizePolicy)
        self.browse_color.setText("")
        self.browse_color.setIcon(icon)
        self.browse_color.setObjectName("browse_color")
        self.horizontalLayout_9.addWidget(self.browse_color)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_2.addWidget(self.label_37)
        self.data_line = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_line.sizePolicy().hasHeightForWidth())
        self.data_line.setSizePolicy(sizePolicy)
        self.data_line.setObjectName("data_line")
        self.horizontalLayout_2.addWidget(self.data_line)
        self.add_data = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_data.sizePolicy().hasHeightForWidth())
        self.add_data.setSizePolicy(sizePolicy)
        self.add_data.setIcon(icon1)
        self.add_data.setObjectName("add_data")
        self.horizontalLayout_2.addWidget(self.add_data)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        DataWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DataWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 26))
        self.menubar.setObjectName("menubar")
        DataWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DataWindow)
        self.statusbar.setObjectName("statusbar")
        DataWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DataWindow)
        QtCore.QMetaObject.connectSlotsByName(DataWindow)

    def retranslateUi(self, DataWindow):
        _translate = QtCore.QCoreApplication.translate
        DataWindow.setWindowTitle(_translate("DataWindow", "MainWindow"))
        self.groupBox_13.setTitle(_translate("DataWindow", "Selected Data"))
        self.selected_data.setSortingEnabled(False)
        self.groupBox.setTitle(_translate("DataWindow", "Info:"))
        self.data_info.setHtml(_translate("DataWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_12.setTitle(_translate("DataWindow", "Opened Functions"))
        self.opened_functions.setSortingEnabled(False)
        self.load_label_14.setText(_translate("DataWindow", "File:"))
        self.label.setText(_translate("DataWindow", "ID:"))
        self.label_35.setText(_translate("DataWindow", "Plot ID:"))
        self.label_36.setText(_translate("DataWindow", "Data ID:"))
        self.label_2.setText(_translate("DataWindow", "Label:"))
        self.label_4.setText(_translate("DataWindow", "Color:"))
        self.label_6.setText(_translate("DataWindow", "RGB"))
        self.label_37.setText(_translate("DataWindow", "Data:"))
        self.add_data.setText(_translate("DataWindow", "Add Data"))
import resources_rc
