# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\file_opening.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileWindow(object):
    def setupUi(self, FileWindow):
        FileWindow.setObjectName("FileWindow")
        FileWindow.resize(422, 356)
        self.centralwidget = QtWidgets.QWidget(FileWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.files_list_wg = QtWidgets.QListWidget(self.groupBox_9)
        self.files_list_wg.setDragEnabled(False)
        self.files_list_wg.setDragDropOverwriteMode(False)
        self.files_list_wg.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.files_list_wg.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.files_list_wg.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.files_list_wg.setLayoutMode(QtWidgets.QListView.Batched)
        self.files_list_wg.setObjectName("files_list_wg")
        self.horizontalLayout_3.addWidget(self.files_list_wg)
        self.verticalLayout_4.addWidget(self.groupBox_9)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.load_label_12 = QtWidgets.QLabel(self.centralwidget)
        self.load_label_12.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_label_12.sizePolicy().hasHeightForWidth())
        self.load_label_12.setSizePolicy(sizePolicy)
        self.load_label_12.setAutoFillBackground(True)
        self.load_label_12.setObjectName("load_label_12")
        self.horizontalLayout_27.addWidget(self.load_label_12)
        self.file_path = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_path.sizePolicy().hasHeightForWidth())
        self.file_path.setSizePolicy(sizePolicy)
        self.file_path.setText("")
        self.file_path.setObjectName("file_path")
        self.horizontalLayout_27.addWidget(self.file_path)
        self.browse_file = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_file.sizePolicy().hasHeightForWidth())
        self.browse_file.setSizePolicy(sizePolicy)
        self.browse_file.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Artigo_remo/ema_fes_rowing_experiments/icons/browse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse_file.setIcon(icon)
        self.browse_file.setObjectName("browse_file")
        self.horizontalLayout_27.addWidget(self.browse_file)
        self.verticalLayout_4.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.add_file = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Artigo_remo/ema_fes_rowing_experiments/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_file.setIcon(icon1)
        self.add_file.setObjectName("add_file")
        self.horizontalLayout_18.addWidget(self.add_file)
        self.rm_file = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Artigo_remo/ema_fes_rowing_experiments/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rm_file.setIcon(icon2)
        self.rm_file.setObjectName("rm_file")
        self.horizontalLayout_18.addWidget(self.rm_file)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        FileWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FileWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 422, 26))
        self.menubar.setObjectName("menubar")
        FileWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FileWindow)
        self.statusbar.setObjectName("statusbar")
        FileWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FileWindow)
        QtCore.QMetaObject.connectSlotsByName(FileWindow)

    def retranslateUi(self, FileWindow):
        _translate = QtCore.QCoreApplication.translate
        FileWindow.setWindowTitle(_translate("FileWindow", "MainWindow"))
        self.groupBox_9.setTitle(_translate("FileWindow", "Opened Files"))
        self.files_list_wg.setSortingEnabled(False)
        self.load_label_12.setText(_translate("FileWindow", "File:"))
        self.add_file.setText(_translate("FileWindow", "Add File"))
        self.rm_file.setText(_translate("FileWindow", "Remove File"))
