# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plot_settings.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotWindow(object):
    def setupUi(self, PlotWindow):
        PlotWindow.setObjectName("PlotWindow")
        PlotWindow.resize(815, 398)
        self.centralwidget = QtWidgets.QWidget(PlotWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(12, 12, 791, 331))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_36 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_13.addWidget(self.label_36)
        self.plot_id = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_id.sizePolicy().hasHeightForWidth())
        self.plot_id.setSizePolicy(sizePolicy)
        self.plot_id.setObjectName("plot_id")
        self.horizontalLayout_13.addWidget(self.plot_id)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_39 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_20.addWidget(self.label_39)
        self.title_plot = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_plot.sizePolicy().hasHeightForWidth())
        self.title_plot.setSizePolicy(sizePolicy)
        self.title_plot.setText("")
        self.title_plot.setObjectName("title_plot")
        self.horizontalLayout_20.addWidget(self.title_plot)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_40 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_25.addWidget(self.label_40)
        self.x_label = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_label.sizePolicy().hasHeightForWidth())
        self.x_label.setSizePolicy(sizePolicy)
        self.x_label.setObjectName("x_label")
        self.horizontalLayout_25.addWidget(self.x_label)
        self.verticalLayout_13.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_41 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_26.addWidget(self.label_41)
        self.y_label = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_label.sizePolicy().hasHeightForWidth())
        self.y_label.setSizePolicy(sizePolicy)
        self.y_label.setObjectName("y_label")
        self.horizontalLayout_26.addWidget(self.y_label)
        self.verticalLayout_13.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_22.addWidget(self.label_8)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_4.sizePolicy().hasHeightForWidth())
        self.spinBox_4.setSizePolicy(sizePolicy)
        self.spinBox_4.setMaximum(255)
        self.spinBox_4.setProperty("value", 255)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_22.addWidget(self.spinBox_4)
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_5.sizePolicy().hasHeightForWidth())
        self.spinBox_5.setSizePolicy(sizePolicy)
        self.spinBox_5.setMaximum(255)
        self.spinBox_5.setProperty("value", 255)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_22.addWidget(self.spinBox_5)
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_6.sizePolicy().hasHeightForWidth())
        self.spinBox_6.setSizePolicy(sizePolicy)
        self.spinBox_6.setMaximum(255)
        self.spinBox_6.setProperty("value", 255)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_22.addWidget(self.spinBox_6)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_22.addWidget(self.label_5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_24.addWidget(self.label_10)
        self.spinBox_8 = QtWidgets.QSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_8.sizePolicy().hasHeightForWidth())
        self.spinBox_8.setSizePolicy(sizePolicy)
        self.spinBox_8.setMaximum(255)
        self.spinBox_8.setProperty("value", 0)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_24.addWidget(self.spinBox_8)
        self.spinBox_9 = QtWidgets.QSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_9.sizePolicy().hasHeightForWidth())
        self.spinBox_9.setSizePolicy(sizePolicy)
        self.spinBox_9.setMaximum(255)
        self.spinBox_9.setProperty("value", 0)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_24.addWidget(self.spinBox_9)
        self.spinBox_10 = QtWidgets.QSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_10.sizePolicy().hasHeightForWidth())
        self.spinBox_10.setSizePolicy(sizePolicy)
        self.spinBox_10.setMaximum(255)
        self.spinBox_10.setProperty("value", 0)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_24.addWidget(self.spinBox_10)
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_24.addWidget(self.label_7)
        self.verticalLayout_13.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.ca_plot_button = QtWidgets.QPushButton(self.groupBox_7)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ca_plot_button.setIcon(icon)
        self.ca_plot_button.setObjectName("ca_plot_button")
        self.horizontalLayout_23.addWidget(self.ca_plot_button)
        self.rm_plot_button = QtWidgets.QPushButton(self.groupBox_7)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rm_plot_button.setIcon(icon1)
        self.rm_plot_button.setObjectName("rm_plot_button")
        self.horizontalLayout_23.addWidget(self.rm_plot_button)
        self.verticalLayout_13.addLayout(self.horizontalLayout_23)
        self.verticalLayout_6.addWidget(self.groupBox_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inactive_plots = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inactive_plots.sizePolicy().hasHeightForWidth())
        self.inactive_plots.setSizePolicy(sizePolicy)
        self.inactive_plots.setAutoScroll(False)
        self.inactive_plots.setProperty("showDropIndicator", False)
        self.inactive_plots.setDragEnabled(True)
        self.inactive_plots.setDragDropOverwriteMode(False)
        self.inactive_plots.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.inactive_plots.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.inactive_plots.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.inactive_plots.setLayoutMode(QtWidgets.QListView.Batched)
        self.inactive_plots.setUniformItemSizes(False)
        self.inactive_plots.setObjectName("inactive_plots")
        self.horizontalLayout.addWidget(self.inactive_plots)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upper_plots = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upper_plots.sizePolicy().hasHeightForWidth())
        self.upper_plots.setSizePolicy(sizePolicy)
        self.upper_plots.setAutoScroll(False)
        self.upper_plots.setProperty("showDropIndicator", False)
        self.upper_plots.setDragEnabled(True)
        self.upper_plots.setDragDropOverwriteMode(False)
        self.upper_plots.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.upper_plots.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.upper_plots.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.upper_plots.setObjectName("upper_plots")
        self.verticalLayout.addWidget(self.upper_plots)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lower_plots = QtWidgets.QListWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lower_plots.sizePolicy().hasHeightForWidth())
        self.lower_plots.setSizePolicy(sizePolicy)
        self.lower_plots.setProperty("showDropIndicator", False)
        self.lower_plots.setDragEnabled(True)
        self.lower_plots.setDragDropOverwriteMode(False)
        self.lower_plots.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lower_plots.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lower_plots.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.lower_plots.setObjectName("lower_plots")
        self.verticalLayout_2.addWidget(self.lower_plots)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.data_list = QtWidgets.QListWidget(self.groupBox_8)
        self.data_list.setDragEnabled(True)
        self.data_list.setDragDropOverwriteMode(True)
        self.data_list.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.data_list.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.data_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.data_list.setLayoutMode(QtWidgets.QListView.Batched)
        self.data_list.setObjectName("data_list")
        self.verticalLayout_3.addWidget(self.data_list)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.add_data_button = QtWidgets.QPushButton(self.groupBox_8)
        self.add_data_button.setIcon(icon)
        self.add_data_button.setObjectName("add_data_button")
        self.horizontalLayout_10.addWidget(self.add_data_button)
        self.rm_data_button = QtWidgets.QPushButton(self.groupBox_8)
        self.rm_data_button.setIcon(icon1)
        self.rm_data_button.setObjectName("rm_data_button")
        self.horizontalLayout_10.addWidget(self.rm_data_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.verticalLayout_5.addWidget(self.groupBox_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        PlotWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PlotWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 26))
        self.menubar.setObjectName("menubar")
        PlotWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PlotWindow)
        self.statusbar.setObjectName("statusbar")
        PlotWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlotWindow)
        QtCore.QMetaObject.connectSlotsByName(PlotWindow)

    def retranslateUi(self, PlotWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotWindow.setWindowTitle(_translate("PlotWindow", "MainWindow"))
        self.groupBox_7.setTitle(_translate("PlotWindow", "Plot Settings"))
        self.label_36.setText(_translate("PlotWindow", "Plot ID:"))
        self.label_39.setText(_translate("PlotWindow", "Title:"))
        self.label_40.setText(_translate("PlotWindow", "X Label:"))
        self.label_41.setText(_translate("PlotWindow", "Y Label:"))
        self.label_8.setText(_translate("PlotWindow", "BG:"))
        self.label_5.setText(_translate("PlotWindow", "RGB"))
        self.label_10.setText(_translate("PlotWindow", "Axis:"))
        self.label_7.setText(_translate("PlotWindow", "RGB"))
        self.ca_plot_button.setText(_translate("PlotWindow", "Create/Alter"))
        self.rm_plot_button.setText(_translate("PlotWindow", "Remove"))
        self.groupBox.setTitle(_translate("PlotWindow", "Inactive Plots"))
        self.inactive_plots.setSortingEnabled(True)
        self.groupBox_2.setTitle(_translate("PlotWindow", "Upper Plots"))
        self.upper_plots.setSortingEnabled(True)
        self.groupBox_5.setTitle(_translate("PlotWindow", "Lower Plots"))
        self.lower_plots.setSortingEnabled(True)
        self.groupBox_8.setTitle(_translate("PlotWindow", "Data"))
        self.data_list.setSortingEnabled(True)
        self.add_data_button.setText(_translate("PlotWindow", "Add Data"))
        self.rm_data_button.setText(_translate("PlotWindow", "Remove Data"))
import resources_rc
