# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\processing_interface.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 1031)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.img_label_upper = QtWidgets.QLabel(self.centralwidget)
        self.img_label_upper.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_label_upper.sizePolicy().hasHeightForWidth())
        self.img_label_upper.setSizePolicy(sizePolicy)
        self.img_label_upper.setMinimumSize(QtCore.QSize(400, 380))
        self.img_label_upper.setAutoFillBackground(False)
        self.img_label_upper.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.img_label_upper.setText("")
        self.img_label_upper.setObjectName("img_label_upper")
        self.horizontalLayout_7.addWidget(self.img_label_upper)
        self.window_plot_upper = GraphWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window_plot_upper.sizePolicy().hasHeightForWidth())
        self.window_plot_upper.setSizePolicy(sizePolicy)
        self.window_plot_upper.setMinimumSize(QtCore.QSize(0, 400))
        self.window_plot_upper.setObjectName("window_plot_upper")
        self.horizontalLayout_7.addWidget(self.window_plot_upper)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.img_label_lower = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_label_lower.sizePolicy().hasHeightForWidth())
        self.img_label_lower.setSizePolicy(sizePolicy)
        self.img_label_lower.setMinimumSize(QtCore.QSize(400, 380))
        self.img_label_lower.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.img_label_lower.setText("")
        self.img_label_lower.setObjectName("img_label_lower")
        self.horizontalLayout_8.addWidget(self.img_label_lower)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.window_plot_lower = GraphWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window_plot_lower.sizePolicy().hasHeightForWidth())
        self.window_plot_lower.setSizePolicy(sizePolicy)
        self.window_plot_lower.setObjectName("window_plot_lower")
        self.horizontalLayout_11.addWidget(self.window_plot_lower)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pp_button = QtWidgets.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Artigo_remo/ema_fes_rowing_experiments/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pp_button.setIcon(icon)
        self.pp_button.setObjectName("pp_button")
        self.horizontalLayout.addWidget(self.pp_button)
        self.speed_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed_label.sizePolicy().hasHeightForWidth())
        self.speed_label.setSizePolicy(sizePolicy)
        self.speed_label.setObjectName("speed_label")
        self.horizontalLayout.addWidget(self.speed_label)
        self.speed_n = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.speed_n.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.speed_n.setMinimum(0.25)
        self.speed_n.setSingleStep(0.25)
        self.speed_n.setProperty("value", 1.0)
        self.speed_n.setObjectName("speed_n")
        self.horizontalLayout.addWidget(self.speed_n)
        self.frame_slider = QtWidgets.QSlider(self.centralwidget)
        self.frame_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.horizontalLayout.addWidget(self.frame_slider)
        self.frame_n = QtWidgets.QSpinBox(self.centralwidget)
        self.frame_n.setMaximum(99)
        self.frame_n.setObjectName("frame_n")
        self.horizontalLayout.addWidget(self.frame_n)
        self.time_video = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_video.sizePolicy().hasHeightForWidth())
        self.time_video.setSizePolicy(sizePolicy)
        self.time_video.setObjectName("time_video")
        self.horizontalLayout.addWidget(self.time_video)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_14.addLayout(self.verticalLayout_4)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.load_label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.load_label_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_label_3.sizePolicy().hasHeightForWidth())
        self.load_label_3.setSizePolicy(sizePolicy)
        self.load_label_3.setAutoFillBackground(True)
        self.load_label_3.setObjectName("load_label_3")
        self.horizontalLayout_18.addWidget(self.load_label_3)
        self.imu_path = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imu_path.sizePolicy().hasHeightForWidth())
        self.imu_path.setSizePolicy(sizePolicy)
        self.imu_path.setText("")
        self.imu_path.setObjectName("imu_path")
        self.horizontalLayout_18.addWidget(self.imu_path)
        self.browse_imu = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_imu.sizePolicy().hasHeightForWidth())
        self.browse_imu.setSizePolicy(sizePolicy)
        self.browse_imu.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Artigo_remo/ema_fes_rowing_experiments/icons/browse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse_imu.setIcon(icon1)
        self.browse_imu.setObjectName("browse_imu")
        self.horizontalLayout_18.addWidget(self.browse_imu)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.forearm_id = QtWidgets.QSpinBox(self.groupBox_4)
        self.forearm_id.setProperty("value", 3)
        self.forearm_id.setObjectName("forearm_id")
        self.horizontalLayout_3.addWidget(self.forearm_id)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.arm_id = QtWidgets.QSpinBox(self.groupBox_4)
        self.arm_id.setProperty("value", 4)
        self.arm_id.setObjectName("arm_id")
        self.horizontalLayout_3.addWidget(self.arm_id)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_2)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.load_label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.load_label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_label_2.sizePolicy().hasHeightForWidth())
        self.load_label_2.setSizePolicy(sizePolicy)
        self.load_label_2.setAutoFillBackground(True)
        self.load_label_2.setObjectName("load_label_2")
        self.horizontalLayout_17.addWidget(self.load_label_2)
        self.stim_path = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stim_path.sizePolicy().hasHeightForWidth())
        self.stim_path.setSizePolicy(sizePolicy)
        self.stim_path.setText("")
        self.stim_path.setObjectName("stim_path")
        self.horizontalLayout_17.addWidget(self.stim_path)
        self.browse_stim = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_stim.sizePolicy().hasHeightForWidth())
        self.browse_stim.setSizePolicy(sizePolicy)
        self.browse_stim.setText("")
        self.browse_stim.setIcon(icon1)
        self.browse_stim.setObjectName("browse_stim")
        self.horizontalLayout_17.addWidget(self.browse_stim)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.load_label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.load_label_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_label_4.sizePolicy().hasHeightForWidth())
        self.load_label_4.setSizePolicy(sizePolicy)
        self.load_label_4.setAutoFillBackground(True)
        self.load_label_4.setObjectName("load_label_4")
        self.horizontalLayout_19.addWidget(self.load_label_4)
        self.pos_path = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_path.sizePolicy().hasHeightForWidth())
        self.pos_path.setSizePolicy(sizePolicy)
        self.pos_path.setText("")
        self.pos_path.setObjectName("pos_path")
        self.horizontalLayout_19.addWidget(self.pos_path)
        self.browse_pos = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_pos.sizePolicy().hasHeightForWidth())
        self.browse_pos.setSizePolicy(sizePolicy)
        self.browse_pos.setText("")
        self.browse_pos.setIcon(icon1)
        self.browse_pos.setObjectName("browse_pos")
        self.horizontalLayout_19.addWidget(self.browse_pos)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.load_label = QtWidgets.QLabel(self.groupBox_4)
        self.load_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_label.sizePolicy().hasHeightForWidth())
        self.load_label.setSizePolicy(sizePolicy)
        self.load_label.setAutoFillBackground(True)
        self.load_label.setObjectName("load_label")
        self.horizontalLayout_16.addWidget(self.load_label)
        self.vid_path = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vid_path.sizePolicy().hasHeightForWidth())
        self.vid_path.setSizePolicy(sizePolicy)
        self.vid_path.setText("")
        self.vid_path.setObjectName("vid_path")
        self.horizontalLayout_16.addWidget(self.vid_path)
        self.browse_video = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_video.sizePolicy().hasHeightForWidth())
        self.browse_video.setSizePolicy(sizePolicy)
        self.browse_video.setText("")
        self.browse_video.setIcon(icon1)
        self.browse_video.setObjectName("browse_video")
        self.horizontalLayout_16.addWidget(self.browse_video)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.load_label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.load_label_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_label_6.sizePolicy().hasHeightForWidth())
        self.load_label_6.setSizePolicy(sizePolicy)
        self.load_label_6.setAutoFillBackground(True)
        self.load_label_6.setObjectName("load_label_6")
        self.horizontalLayout_21.addWidget(self.load_label_6)
        self.vidtime_path = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vidtime_path.sizePolicy().hasHeightForWidth())
        self.vidtime_path.setSizePolicy(sizePolicy)
        self.vidtime_path.setText("")
        self.vidtime_path.setObjectName("vidtime_path")
        self.horizontalLayout_21.addWidget(self.vidtime_path)
        self.browse_vidtime = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_vidtime.sizePolicy().hasHeightForWidth())
        self.browse_vidtime.setSizePolicy(sizePolicy)
        self.browse_vidtime.setText("")
        self.browse_vidtime.setIcon(icon1)
        self.browse_vidtime.setObjectName("browse_vidtime")
        self.horizontalLayout_21.addWidget(self.browse_vidtime)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.load_label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.load_label_12.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_label_12.sizePolicy().hasHeightForWidth())
        self.load_label_12.setSizePolicy(sizePolicy)
        self.load_label_12.setAutoFillBackground(True)
        self.load_label_12.setObjectName("load_label_12")
        self.horizontalLayout_27.addWidget(self.load_label_12)
        self.out_path = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out_path.sizePolicy().hasHeightForWidth())
        self.out_path.setSizePolicy(sizePolicy)
        self.out_path.setText("")
        self.out_path.setObjectName("out_path")
        self.horizontalLayout_27.addWidget(self.out_path)
        self.browse_out = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_out.sizePolicy().hasHeightForWidth())
        self.browse_out.setSizePolicy(sizePolicy)
        self.browse_out.setText("")
        self.browse_out.setIcon(icon1)
        self.browse_out.setObjectName("browse_out")
        self.horizontalLayout_27.addWidget(self.browse_out)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.load_label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.load_label_13.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_label_13.sizePolicy().hasHeightForWidth())
        self.load_label_13.setSizePolicy(sizePolicy)
        self.load_label_13.setAutoFillBackground(True)
        self.load_label_13.setObjectName("load_label_13")
        self.horizontalLayout_28.addWidget(self.load_label_13)
        self.feat_path = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feat_path.sizePolicy().hasHeightForWidth())
        self.feat_path.setSizePolicy(sizePolicy)
        self.feat_path.setText("")
        self.feat_path.setObjectName("feat_path")
        self.horizontalLayout_28.addWidget(self.feat_path)
        self.browse_feat = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_feat.sizePolicy().hasHeightForWidth())
        self.browse_feat.setSizePolicy(sizePolicy)
        self.browse_feat.setText("")
        self.browse_feat.setIcon(icon1)
        self.browse_feat.setObjectName("browse_feat")
        self.horizontalLayout_28.addWidget(self.browse_feat)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.load_label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.load_label_14.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_label_14.sizePolicy().hasHeightForWidth())
        self.load_label_14.setSizePolicy(sizePolicy)
        self.load_label_14.setAutoFillBackground(True)
        self.load_label_14.setObjectName("load_label_14")
        self.horizontalLayout_29.addWidget(self.load_label_14)
        self.pred_path = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pred_path.sizePolicy().hasHeightForWidth())
        self.pred_path.setSizePolicy(sizePolicy)
        self.pred_path.setText("")
        self.pred_path.setObjectName("pred_path")
        self.horizontalLayout_29.addWidget(self.pred_path)
        self.browse_pred = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_pred.sizePolicy().hasHeightForWidth())
        self.browse_pred.setSizePolicy(sizePolicy)
        self.browse_pred.setText("")
        self.browse_pred.setIcon(icon1)
        self.browse_pred.setObjectName("browse_pred")
        self.horizontalLayout_29.addWidget(self.browse_pred)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.verticalLayout_9.addWidget(self.groupBox_4)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_36 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_13.addWidget(self.label_36)
        self.plt_set_ul = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plt_set_ul.sizePolicy().hasHeightForWidth())
        self.plt_set_ul.setSizePolicy(sizePolicy)
        self.plt_set_ul.setEditable(True)
        self.plt_set_ul.setObjectName("plt_set_ul")
        self.plt_set_ul.addItem("")
        self.plt_set_ul.addItem("")
        self.horizontalLayout_13.addWidget(self.plt_set_ul)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.plot_n_set = QtWidgets.QSpinBox(self.groupBox_7)
        self.plot_n_set.setMinimum(1)
        self.plot_n_set.setMaximum(4)
        self.plot_n_set.setObjectName("plot_n_set")
        self.horizontalLayout_13.addWidget(self.plot_n_set)
        self.segment = QtWidgets.QCheckBox(self.groupBox_7)
        self.segment.setObjectName("segment")
        self.horizontalLayout_13.addWidget(self.segment)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_39 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_20.addWidget(self.label_39)
        self.title_plot = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_plot.sizePolicy().hasHeightForWidth())
        self.title_plot.setSizePolicy(sizePolicy)
        self.title_plot.setText("")
        self.title_plot.setObjectName("title_plot")
        self.horizontalLayout_20.addWidget(self.title_plot)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_40 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_25.addWidget(self.label_40)
        self.x_label = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_label.sizePolicy().hasHeightForWidth())
        self.x_label.setSizePolicy(sizePolicy)
        self.x_label.setObjectName("x_label")
        self.horizontalLayout_25.addWidget(self.x_label)
        self.verticalLayout_13.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_41 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_26.addWidget(self.label_41)
        self.y_label = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_label.sizePolicy().hasHeightForWidth())
        self.y_label.setSizePolicy(sizePolicy)
        self.y_label.setObjectName("y_label")
        self.horizontalLayout_26.addWidget(self.y_label)
        self.verticalLayout_13.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_22.addWidget(self.label_8)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_4.sizePolicy().hasHeightForWidth())
        self.spinBox_4.setSizePolicy(sizePolicy)
        self.spinBox_4.setMaximum(255)
        self.spinBox_4.setProperty("value", 255)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_22.addWidget(self.spinBox_4)
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_5.sizePolicy().hasHeightForWidth())
        self.spinBox_5.setSizePolicy(sizePolicy)
        self.spinBox_5.setMaximum(255)
        self.spinBox_5.setProperty("value", 255)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_22.addWidget(self.spinBox_5)
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_6.sizePolicy().hasHeightForWidth())
        self.spinBox_6.setSizePolicy(sizePolicy)
        self.spinBox_6.setMaximum(255)
        self.spinBox_6.setProperty("value", 255)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_22.addWidget(self.spinBox_6)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_22.addWidget(self.label_5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_24.addWidget(self.label_10)
        self.spinBox_8 = QtWidgets.QSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_8.sizePolicy().hasHeightForWidth())
        self.spinBox_8.setSizePolicy(sizePolicy)
        self.spinBox_8.setMaximum(255)
        self.spinBox_8.setProperty("value", 0)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_24.addWidget(self.spinBox_8)
        self.spinBox_9 = QtWidgets.QSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_9.sizePolicy().hasHeightForWidth())
        self.spinBox_9.setSizePolicy(sizePolicy)
        self.spinBox_9.setMaximum(255)
        self.spinBox_9.setProperty("value", 0)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_24.addWidget(self.spinBox_9)
        self.spinBox_10 = QtWidgets.QSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_10.sizePolicy().hasHeightForWidth())
        self.spinBox_10.setSizePolicy(sizePolicy)
        self.spinBox_10.setMaximum(255)
        self.spinBox_10.setProperty("value", 0)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_24.addWidget(self.spinBox_10)
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_24.addWidget(self.label_7)
        self.verticalLayout_13.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.ca_plot_button = QtWidgets.QPushButton(self.groupBox_7)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Artigo_remo/ema_fes_rowing_experiments/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ca_plot_button.setIcon(icon2)
        self.ca_plot_button.setObjectName("ca_plot_button")
        self.horizontalLayout_23.addWidget(self.ca_plot_button)
        self.rm_plot_button = QtWidgets.QPushButton(self.groupBox_7)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Artigo_remo/ema_fes_rowing_experiments/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rm_plot_button.setIcon(icon3)
        self.rm_plot_button.setObjectName("rm_plot_button")
        self.horizontalLayout_23.addWidget(self.rm_plot_button)
        self.verticalLayout_13.addLayout(self.horizontalLayout_23)
        self.verticalLayout_9.addWidget(self.groupBox_7)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_38 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_15.addWidget(self.label_38)
        self.data_set_ul = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_set_ul.sizePolicy().hasHeightForWidth())
        self.data_set_ul.setSizePolicy(sizePolicy)
        self.data_set_ul.setEditable(True)
        self.data_set_ul.setObjectName("data_set_ul")
        self.data_set_ul.addItem("")
        self.data_set_ul.addItem("")
        self.horizontalLayout_15.addWidget(self.data_set_ul)
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.data_n_set = QtWidgets.QSpinBox(self.groupBox_6)
        self.data_n_set.setMinimum(1)
        self.data_n_set.setMaximum(4)
        self.data_n_set.setProperty("value", 1)
        self.data_n_set.setObjectName("data_n_set")
        self.horizontalLayout_15.addWidget(self.data_n_set)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_34 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_4.addWidget(self.label_34)
        self.file_data_set = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_data_set.sizePolicy().hasHeightForWidth())
        self.file_data_set.setSizePolicy(sizePolicy)
        self.file_data_set.setEditable(False)
        self.file_data_set.setObjectName("file_data_set")
        self.file_data_set.addItem("")
        self.file_data_set.addItem("")
        self.file_data_set.addItem("")
        self.file_data_set.addItem("")
        self.file_data_set.addItem("")
        self.file_data_set.addItem("")
        self.horizontalLayout_4.addWidget(self.file_data_set)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_37 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_5.addWidget(self.label_37)
        self.elem_data_set = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elem_data_set.sizePolicy().hasHeightForWidth())
        self.elem_data_set.setSizePolicy(sizePolicy)
        self.elem_data_set.setEditable(False)
        self.elem_data_set.setObjectName("elem_data_set")
        self.elem_data_set.addItem("")
        self.horizontalLayout_5.addWidget(self.elem_data_set)
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.scale_cb = QtWidgets.QCheckBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_cb.sizePolicy().hasHeightForWidth())
        self.scale_cb.setSizePolicy(sizePolicy)
        self.scale_cb.setText("")
        self.scale_cb.setObjectName("scale_cb")
        self.horizontalLayout_5.addWidget(self.scale_cb)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_42 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_31.addWidget(self.label_42)
        self.apply_processing = QtWidgets.QCheckBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_processing.sizePolicy().hasHeightForWidth())
        self.apply_processing.setSizePolicy(sizePolicy)
        self.apply_processing.setText("")
        self.apply_processing.setObjectName("apply_processing")
        self.horizontalLayout_31.addWidget(self.apply_processing)
        self.processing_function = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processing_function.sizePolicy().hasHeightForWidth())
        self.processing_function.setSizePolicy(sizePolicy)
        self.processing_function.setObjectName("processing_function")
        self.horizontalLayout_31.addWidget(self.processing_function)
        self.browse_processing = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_processing.sizePolicy().hasHeightForWidth())
        self.browse_processing.setSizePolicy(sizePolicy)
        self.browse_processing.setText("")
        self.browse_processing.setIcon(icon1)
        self.browse_processing.setObjectName("browse_processing")
        self.horizontalLayout_31.addWidget(self.browse_processing)
        self.verticalLayout_12.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_6.addWidget(self.label_35)
        self.label_data_set = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_set.sizePolicy().hasHeightForWidth())
        self.label_data_set.setSizePolicy(sizePolicy)
        self.label_data_set.setObjectName("label_data_set")
        self.horizontalLayout_6.addWidget(self.label_data_set)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.data_R_n = QtWidgets.QSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_R_n.sizePolicy().hasHeightForWidth())
        self.data_R_n.setSizePolicy(sizePolicy)
        self.data_R_n.setMaximum(255)
        self.data_R_n.setObjectName("data_R_n")
        self.horizontalLayout_9.addWidget(self.data_R_n)
        self.data_G_n = QtWidgets.QSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_G_n.sizePolicy().hasHeightForWidth())
        self.data_G_n.setSizePolicy(sizePolicy)
        self.data_G_n.setMaximum(255)
        self.data_G_n.setObjectName("data_G_n")
        self.horizontalLayout_9.addWidget(self.data_G_n)
        self.data_B_n = QtWidgets.QSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_B_n.sizePolicy().hasHeightForWidth())
        self.data_B_n.setSizePolicy(sizePolicy)
        self.data_B_n.setMaximum(255)
        self.data_B_n.setProperty("value", 255)
        self.data_B_n.setObjectName("data_B_n")
        self.horizontalLayout_9.addWidget(self.data_B_n)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.add_data_button = QtWidgets.QPushButton(self.groupBox_6)
        self.add_data_button.setIcon(icon2)
        self.add_data_button.setObjectName("add_data_button")
        self.horizontalLayout_10.addWidget(self.add_data_button)
        self.rm_data_button = QtWidgets.QPushButton(self.groupBox_6)
        self.rm_data_button.setIcon(icon3)
        self.rm_data_button.setObjectName("rm_data_button")
        self.horizontalLayout_10.addWidget(self.rm_data_button)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.verticalLayout_9.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_2.addWidget(self.label_31)
        self.interval = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.interval.setProperty("value", 20.0)
        self.interval.setObjectName("interval")
        self.horizontalLayout_2.addWidget(self.interval)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_12.addWidget(self.label_32)
        self.ymax = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.ymax.setObjectName("ymax")
        self.horizontalLayout_12.addWidget(self.ymax)
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_12.addWidget(self.label_33)
        self.ymin = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.ymin.setObjectName("ymin")
        self.horizontalLayout_12.addWidget(self.ymin)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.verticalLayout_9.addWidget(self.groupBox_5)
        self.horizontalLayout_14.addLayout(self.verticalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pp_button.setText(_translate("MainWindow", "Play"))
        self.speed_label.setText(_translate("MainWindow", "Speed:"))
        self.time_video.setText(_translate("MainWindow", "00:00 / 00:00"))
        self.groupBox_4.setTitle(_translate("MainWindow", "File Settings"))
        self.load_label_3.setText(_translate("MainWindow", "IMU:"))
        self.label.setText(_translate("MainWindow", "Forearm ID"))
        self.label_2.setText(_translate("MainWindow", "Arm ID"))
        self.load_label_2.setText(_translate("MainWindow", "Stim:"))
        self.load_label_4.setText(_translate("MainWindow", "Pos:"))
        self.load_label.setText(_translate("MainWindow", "Video:"))
        self.load_label_6.setText(_translate("MainWindow", "Time:"))
        self.load_label_12.setText(_translate("MainWindow", "Out:"))
        self.load_label_13.setText(_translate("MainWindow", "Feat:"))
        self.load_label_14.setText(_translate("MainWindow", "Pred:"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Plot Settings"))
        self.label_36.setText(_translate("MainWindow", "Plot:"))
        self.plt_set_ul.setItemText(0, _translate("MainWindow", "Upper"))
        self.plt_set_ul.setItemText(1, _translate("MainWindow", "Lower"))
        self.label_9.setText(_translate("MainWindow", "Num:"))
        self.segment.setText(_translate("MainWindow", "Seg."))
        self.label_39.setText(_translate("MainWindow", "Title:"))
        self.label_40.setText(_translate("MainWindow", "X Label:"))
        self.label_41.setText(_translate("MainWindow", "Y Label:"))
        self.label_8.setText(_translate("MainWindow", "BG:"))
        self.label_5.setText(_translate("MainWindow", "RGB"))
        self.label_10.setText(_translate("MainWindow", "Axis:"))
        self.label_7.setText(_translate("MainWindow", "RGB"))
        self.ca_plot_button.setText(_translate("MainWindow", "Create/Alter"))
        self.rm_plot_button.setText(_translate("MainWindow", "Remove"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Data Settings"))
        self.label_38.setText(_translate("MainWindow", "Plot:"))
        self.data_set_ul.setItemText(0, _translate("MainWindow", "Upper"))
        self.data_set_ul.setItemText(1, _translate("MainWindow", "Lower"))
        self.label_11.setText(_translate("MainWindow", "Number:"))
        self.label_34.setText(_translate("MainWindow", "File: "))
        self.file_data_set.setCurrentText(_translate("MainWindow", "Pos"))
        self.file_data_set.setItemText(0, _translate("MainWindow", "Pos"))
        self.file_data_set.setItemText(1, _translate("MainWindow", "IMU"))
        self.file_data_set.setItemText(2, _translate("MainWindow", "Stim"))
        self.file_data_set.setItemText(3, _translate("MainWindow", "Out"))
        self.file_data_set.setItemText(4, _translate("MainWindow", "Feat"))
        self.file_data_set.setItemText(5, _translate("MainWindow", "Pred"))
        self.label_37.setText(_translate("MainWindow", "Elem:"))
        self.elem_data_set.setItemText(0, _translate("MainWindow", "seat position"))
        self.label_3.setText(_translate("MainWindow", "Scale:"))
        self.label_42.setText(_translate("MainWindow", "Apply:"))
        self.label_35.setText(_translate("MainWindow", "Label:"))
        self.label_4.setText(_translate("MainWindow", "Color:"))
        self.label_6.setText(_translate("MainWindow", "RGB"))
        self.add_data_button.setText(_translate("MainWindow", "Add Data"))
        self.rm_data_button.setText(_translate("MainWindow", "Remove Data"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Position Settings"))
        self.label_31.setText(_translate("MainWindow", "Interval (s): "))
        self.label_32.setText(_translate("MainWindow", "Y Max: "))
        self.label_33.setText(_translate("MainWindow", "Y Min: "))
from pyqtgraph_class import GraphWidget
